FROM node:alpine


ARG ETHEREUM_ADMIN_PRIVATE_KEY
ENV ETHEREUM_ADMIN_PRIVATE_KEY=$ETHEREUM_ADMIN_PRIVATE_KEY

ARG ETHEREUM_ADMIN_ACCOUNT
ENV ETHEREUM_ADMIN_ACCOUNT=$ETHEREUM_ADMIN_ACCOUNT

ARG SUPPORTED_PAIRS
ENV SUPPORTED_PAIRS=$SUPPORTED_PAIRS

ARG ROOT_PRICE_ORACLE_CONTRACT_ADDRESS
ENV ROOT_PRICE_ORACLE_CONTRACT_ADDRESS=$ROOT_PRICE_ORACLE_CONTRACT_ADDRESS

ARG WEB3_HTTP_PROVIDER_URL
ENV WEB3_HTTP_PROVIDER_URL=$WEB3_HTTP_PROVIDER_URL

COPY . .

RUN npm install pm2 -g && npm install


CMD ["pm2-runtime", "ecosystem.config.js"]
